[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "plans"
version = "0.1.0"
description = "PLANS - Planning Nature-based Solutions"
authors = [{name = "Ipo", email = "possantti@gmail.com"}]
